# Introduction to NumPy

The content of this section is derived from the book "Python data science hanbdbook". Details of this book can be found  in the further reading section.

[NumPy](https://numpy.org/) is a scientific computing library and is the defacto library for numerical analysis and linear algebra in python i.e. it is "__Nu__merical __Py__thon". It is a bit like __Matlab__ for python.  One of its
primary features is the provision of efficient array data structures which are not particularly well supported in
base python.

## Arrays using Python Lists

An array like structure can be created in python using lists.

### <u>Example 1</u>

In [2]:
A = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]


In [4]:
A[1][2]

6

In python, arrays represented as lists or, in the multidimensianal setting, lists of lists of lists ..., have the advantage of being __inhomogenous__. However, when compared to arrays in other languages (which are commonly homogenous), they are not very efficient for __random access__. 

The following diagram shows a one dimensional array and the equivalent one dimensional list. Because an array is __contiguous__ in memory, (no gaps in between successive data elements) it is possible to access the data very quickly using simple arithmetic. However, in a list, to get to value 17, you would have to start at 23 and march forward 2 places visiting 3 on the way. As the list grows, this repeated starting at the beginning and moving on becomes very expensive. 

Python does come with an array type, but it is not particularly easy to use and is not well optimized for some of the more common array like operations.


__array__
![arrays vs lists](figs/array-list.png)
__list__



[source](https://dzone.com/storage/temp/895349-arraylist-linkedlistt.png)

## NumPy arrays

Installing numpy.

In [6]:
! python -m pip install numpy

You should consider upgrading via the '/home/grosedj/python-envs/M550/env/bin/python -m pip install --upgrade pip' command.


Importing the numpy package (note the use of an the "alias" __np__).

In [7]:
import numpy as np

### <u>Exercise 1</u>

Install and import the __numpy__ package.

## Why NumPy Instead Of Python Lists?

In general, there seem to be four possible reasons to prefer NumPy arrays over lists in Python:
- NumPy arrays are more compact than lists.
- access in reading and writing items is faster with NumPy.
- NumPy can be more convenient to work with, thanks to the fact that you get a lot of vector and matrix operations for free
- NumPy can be more efficient to work with because they are implemented more efficiently.

## Creating and acessing NumPy arrays

### <u>Example 2 - creating NumPy array from a list</u>

In [127]:
X = np.array([[1,2,3],[4,5,6]])
print(X)

[[1 2 3]
 [4 5 6]]


### <u>Exercise 2 - indexing tnto a NumPy array</u>

What do you think the output of the following code will be ?


In [128]:
print(X[1,0])
print(X[1])
print(X[1][0])
X[0,2] = 10
print(X)

4
[4 5 6]
4
[[ 1  2 10]
 [ 4  5  6]]


### <u>Exercise 3</u>

Use __help__ function to find out about the following functions that can be used for initialising __NumPy__ arrays.

- __ones__
- __zeros__
- __empty__



In [34]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C', *, like=None)
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this 

### <u>Exercise 4 - creating a NumPy array from scratch</u>

Create a three dimensional numpy array with dimension 3,5,2 that contains floating point numbers. What do the contents look like ? How does this compare with using __zeros__ ? How you create the same array but for use with integer values ?

In [43]:
X = np.empty((3,5,2))
print(X[0])
X = np.empty((3,5,2),dtype="int")
print(X[0])

[[4.64240782e-310 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [6.94720202e-310 5.02034658e+175]
 [1.39493227e+165 6.59009028e-066]
 [6.44941158e-067 1.71730086e+185]]
[[     93963382189312                   0]
 [                  0                   0]
 [1821345658565558272 7235419174270214779]
 [3919930717926079010 7363447183357796659]
 [7221912571268642100 3991932207196550456]]


__NumPy__ has many more basic types of data than base python. They typically map to the basic C types that they are built on.

<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Numpy type</p></th>
<th class="head"><p>C type</p></th>
<th class="head"><p>Description</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.bool_" title="numpy.bool_"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.bool_</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">bool</span></code></p></td>
<td><p>Boolean (True or False) stored as a byte</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.byte" title="numpy.byte"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.byte</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">signed</span> <span class="pre">char</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.ubyte" title="numpy.ubyte"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.ubyte</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">char</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.short" title="numpy.short"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.short</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">short</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.ushort" title="numpy.ushort"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.ushort</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">short</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.intc" title="numpy.intc"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.intc</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">int</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.uintc" title="numpy.uintc"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.uintc</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">int</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.int_" title="numpy.int_"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.int_</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">long</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.uint" title="numpy.uint"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.uint</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">long</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.longlong" title="numpy.longlong"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.longlong</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">long</span> <span class="pre">long</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.ulonglong" title="numpy.ulonglong"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.ulonglong</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">unsigned</span> <span class="pre">long</span> <span class="pre">long</span></code></p></td>
<td><p>Platform-defined</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.half" title="numpy.half"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.half</span></code></a> / <a class="reference internal" href="../reference/arrays.scalars.html#numpy.float16" title="numpy.float16"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.float16</span></code></a></p></td>
<td></td>
<td><p>Half precision float:
sign bit, 5 bits exponent, 10 bits mantissa</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.single" title="numpy.single"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.single</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">float</span></code></p></td>
<td><p>Platform-defined single precision float:
typically sign bit, 8 bits exponent, 23 bits mantissa</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.double" title="numpy.double"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.double</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">double</span></code></p></td>
<td><p>Platform-defined double precision float:
typically sign bit, 11 bits exponent, 52 bits mantissa.</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.longdouble" title="numpy.longdouble"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.longdouble</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">long</span> <span class="pre">double</span></code></p></td>
<td><p>Platform-defined extended-precision float</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.csingle" title="numpy.csingle"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.csingle</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">float</span> <span class="pre">complex</span></code></p></td>
<td><p>Complex number, represented by two single-precision floats (real and imaginary components)</p></td>
</tr>
<tr class="row-even"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.cdouble" title="numpy.cdouble"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.cdouble</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">double</span> <span class="pre">complex</span></code></p></td>
<td><p>Complex number, represented by two double-precision floats (real and imaginary components).</p></td>
</tr>
<tr class="row-odd"><td><p><a class="reference internal" href="../reference/arrays.scalars.html#numpy.clongdouble" title="numpy.clongdouble"><code class="xref py py-obj docutils literal notranslate"><span class="pre">numpy.clongdouble</span></code></a></p></td>
<td><p><code class="docutils literal notranslate"><span class="pre">long</span> <span class="pre">double</span> <span class="pre">complex</span></code></p></td>
<td><p>Complex number, represented by two extended-precision floats (real and imaginary components).</p></td>
</tr>
</tbody>
</table>

## Slicing and accessing subarrays

Subarrays can be access using the format [start:stop:step]. 

### <u>Example 3 - slicing</u>

In [129]:
X = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(X[0:2:1])

[[1 2 3 4]
 [5 6 7 8]]


### <u>Exercise 5</u>

Predict the output of the following code.

In [53]:
print(X[0:3:2])

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [57]:
print(X[0:3:1][:2:1])

[[1 2 3 4]
 [5 6 7 8]]


In [58]:
print(X[0:3:1][:2:2])

[[1 2 3 4]]


In [59]:
print(X[:3:][:2:2])

[[1 2 3 4]]


In [63]:
print(X[:3:,:2:2])

[[1]
 [5]
 [9]]


In [62]:
print(X[::2,::2])

[[ 1  3]
 [ 9 11]]


In [69]:
print(X[1:3:,1:3:])

[[ 6  7]
 [10 11]]


In [74]:
print(X[:,1])

[ 2  6 10 14]


In [75]:
print(X[1,:])

[5 6 7 8]


In [70]:
Z = X[1:3:,1:3:]
Z[1,1] = 20
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 20 12]
 [13 14 15 16]]


Note that in the last example, Z is <u>__NOT__</u> a copy of the data inside X, it is a "__view__" on the data contained in X.
You can create a copy using __copy__.

### <u>Example 4 - copying</u>

In [72]:
Z = X[1:3:,1:3:].copy()
Z[1,1] = 50
print(X)
print(Z)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 20 12]
 [13 14 15 16]]
[[ 6  7]
 [10 50]]


### <u>Exercise 6</u>

Use __help__ to find out how to use the NumPy __reshape__, __concatenate__, __vstack__, and __hstack__  functions.

In [80]:
help(np.concatenate)

Help on function concatenate in module numpy:

concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
    
    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.
    
        .. versionadded:: 1.20.0
    
    casting : {'no', 'equiv', 'safe', '

In [ ]:
The shape of a NumPy array can be found quite easily.

In [102]:
print(X.shape)

(4, 4)


## Random numbers.

The NumPy library is more than an array library. For example, it offers random number generation.

### <u>Example 5 - uniform random numbers</u>

In [82]:
np.random.rand(3,2)

array([[0.3150833 , 0.33404232],
       [0.44625496, 0.54454593],
       [0.56114458, 0.14973511]])

### <u>Exercise 7</u>

Use __help(np.random))__ to find out about random number generation in NumPy. Generate large matrices of random numbers from some of these distributions.

In [85]:
help(np.random.rand)

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [107]:
X = np.random.rand(1000,1000)
print(X[1:10,1:10])

[[0.93725918 0.06203331 0.83580012 0.03160988 0.7798329  0.30640705
  0.7414987  0.99160143 0.14266476]
 [0.95206452 0.14178445 0.09118578 0.17457443 0.76104316 0.28949847
  0.29942323 0.07608373 0.05289887]
 [0.25530272 0.66924424 0.28340527 0.71735581 0.30488826 0.30623068
  0.47408782 0.70436219 0.58647558]
 [0.26812957 0.87237088 0.51070945 0.53435651 0.73995196 0.75998788
  0.58319684 0.65992788 0.70158033]
 [0.24103802 0.19956387 0.74662767 0.84646724 0.12328907 0.26932249
  0.38748918 0.72313705 0.40867608]
 [0.63366512 0.05276984 0.1132461  0.08810961 0.320329   0.31010316
  0.64176265 0.22798977 0.95000039]
 [0.45652143 0.00195218 0.2580788  0.87617122 0.41812466 0.96003646
  0.85651487 0.51288647 0.98163307]
 [0.7487736  0.90593057 0.34325887 0.79687955 0.57725936 0.76379036
  0.73959716 0.75815155 0.50633209]
 [0.60686795 0.98670865 0.01420011 0.23918258 0.77386063 0.12878113
  0.37959095 0.14720258 0.7509649 ]]


### <u>Exercise 8</u>

Write a function that calculates the sine of each value one of the large matrices you generated for excercise 7.

In [108]:
from math import sin
def matsin(X) :
    (n,m) = X.shape
    Y = np.empty((n,m))
    for i in range(n) :
        for j in range(m) :
            Y[i,j] = sin(X[i,j])
    return(Y)

Y = matsin(X)
print(Y[1:10,1:10])

[[0.80593856 0.06199353 0.7418333  0.03160461 0.70316061 0.30163499
  0.6753939  0.8369036  0.14218131]
 [0.81461467 0.14130988 0.09105946 0.17368905 0.68967719 0.2854716
  0.29496915 0.07601035 0.0528742 ]
 [0.25253833 0.62039343 0.27962669 0.65739445 0.30018659 0.30146683
  0.45652706 0.64754793 0.55342899]
 [0.26492831 0.76585559 0.48879629 0.50928736 0.67425243 0.68891266
  0.55069517 0.61305988 0.64542558]
 [0.23871077 0.19824188 0.67916739 0.74894416 0.12297697 0.26607841
  0.37786494 0.66173988 0.39739478]
 [0.59210231 0.05274536 0.1130042  0.08799565 0.31487884 0.30515688
  0.59860833 0.22601977 0.81341573]
 [0.44082845 0.00195218 0.25522345 0.76829373 0.40604739 0.81921248
  0.75556414 0.49069436 0.83140592]
 [0.6807409  0.78699961 0.33655763 0.71517857 0.54572944 0.69166388
  0.67399037 0.68758045 0.48497282]
 [0.57029747 0.83421552 0.01419964 0.23690855 0.69890163 0.12842546
  0.37054057 0.14667154 0.68234445]]


In [ ]:
It is possibe to measure how long code takes to run using %timeit.

### <u>Example 6 - %timeit</u>

In [112]:
%timeit matsin(X)

250 ms ± 6.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## NumPy UFuncs

NumPy’s ufuncs can be used to make repeated calculations on array elements much more efficient. ufuncs apply use vectorization to undertake large numbers of operations using fast compiled C code without having to call the underlying C functions repeatedly. This can make things much faster.

### <u>Exercise 9</u>

Use %timeit to find out how long the following python code takes to run. Compare it to the reuslts you obtained from exercise 8. 

In [113]:
%timeit Y = np.sin(X)

8.88 ms ± 112 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


There are lots of ufuncs in NumPy. They include various operators for example. 



### <u>Example 7</u>

In [117]:
Y = X + X
Y = 2*X
Y = X*X


Note that the * is <u>__NOT__</u> matrix multiplication. For this you have to use the __matmul__ function. 